version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=testeo123
      - MYSQL_DATABASE=geopagosDb
    container_name: geopagosDb
    volumes:
      - ./mysql-data:/var/lib/mysql